name: gpodder_client
dependencies:
  chopper: ^3.0.0
  json_annotation: ^3.0.0

dev_dependencies:
  test:
  build_runner: ^1.0.0
  chopper_generator: ^3.0.0
  json_serializable: ^3.3.0



dependency_overrides:
  analyzer: '0.39.17'
  build_resolvers: '1.3.10'
